; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26128.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\319997.LINCOLNCOLLEGE.001\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
